### ISSUE TITLE
Project is missing appcompat_v7 'libs' directory

### ISSUE THREAD

**Issue by DLLarson** [obastemur/jxcore-android-basics#3]
This project is missing the contents of the appcompat_v7 `libs`. I needed to copy them from the Android SDK from `extras/android/support/v7/appcompat/libs`.

It would be great if they were supplied with the project to reduce confusion.

-Dale

**Comment by obastemur** [comment]
Right now this project targets Android Studio and I believe this problem is no longer exists.
